### ISSUE TITLE
Terraform resource limitation for NSXT LB

### ISSUE THREAD

**Issue by ravishankar1jan** [vmware/terraform-provider-nsxt#1353]
### Describe the bug

I have try to automate NSXT resource provisioning however i am only able to create some of resources in policy mode  (Highlighted in green colour). 

<img width="230" alt="GitHub" src="https://github.com/user-attachments/assets/f815b671-872e-455e-b888-80b3f3aa49cd">

Could you please let me know if anyone has solution to provision resources which are greyed out. 
Please also let me know if additional explanation is required.

### Reproduction steps

-

### Expected behavior

-

### Additional context

-

**Comment by salv-orlando** [comment]
Hello @ravishankar1jan If I try to open the image you attached I get a 404. Can you please comment on which resources are still missing? We have some gaps for NSX LB resources, and planning to fill them in 3.7.0 or 3.8.0 if time does not allows us to.

**Comment by ravishankar1jan** [comment]
@salv-orlando 
Following is status of resources. Where ever there is "X", i am not able to create that resource in policy mode.

Profile-> APPLICATION
============
Fast TCP - X
Fast UDP - X
HTTP - nsxt_policy_lb_http_application_profile

Profile-> Persistence
============
Source IP - X 
Cookie - X
Generic - X

Profile-> SSL
============
Client SSL - nsxt_policy_lb_client_ssl_profile
Server SSL - X 

=================================
Monitor-> All working as expected
Active ->
	  http  - nsxt_policy_lb_http_monitor_profile
	  https - nsxt_policy_lb_https_monitor_profile
	  icmp  - nsxt_policy_lb_icmp_monitor_profile
	  tcp   - nsxt_policy_lb_tcp_monitor_profile
	  udp   - nsxt_policy_lb_udp_monitor_profile
Passive ->
          passive -     nsxt_policy_lb_passive_monitor_profile

Virutal Server
=================
HTTP -> nsxt_policy_lb_virtual_server
TCP -> X
UDP -> X

ServerPool
============
LB Pool - nsxt_policy_lb_pool

<img width="230" alt="GitHub" src="https://github.com/user-attachments/assets/9a3069ad-86c4-4f3f-8a19-494a7d7b8c66">

Please let me know if you need any further details.

Thanks

**Comment by ravishankar1jan** [comment]
Hello Team,
I have tried to create virtual server with rule set using terraform with nsxt provider version 3.6.2 as well as 3.7.0 
However, when i am trying to create with rules it's throwing following error:

╷
│ Error: Plugin did not respond
│ 
│   with module.my_module_name.nsxt_policy_lb_virtual_server.test,
│   on .terraform/modules/my_module_name/virtual-server.tf line 12, in resource "nsxt_policy_lb_virtual_server" "test":
│   12: resource "nsxt_policy_lb_virtual_server" "test" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-nsxt_v3.7.0 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 76 [running]:
github.com/vmware/terraform-provider-nsxt/nsxt.getPolicyLbRulesFromSchema(0xc000778600?)
	github.com/vmware/terraform-provider-nsxt/nsxt/resource_nsxt_policy_lb_virtual_server.go:1416 +0x4997
github.com/vmware/terraform-provider-nsxt/nsxt.resourceNsxtPolicyLBVirtualServerCreate(0xc000778600, {0x1bf5480, 0xc0003f9380})
	github.com/vmware/terraform-provider-nsxt/nsxt/resource_nsxt_policy_lb_virtual_server.go:1619 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1f4a590?, {0x1f4a590?, 0xc000a8f260?}, 0xd?, {0x1bf5480?, 0xc0003f9380?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000195e0, {0x1f4a590, 0xc000a8f260}, 0xc0004bea90, 0xc000778480, {0x1bf5480, 0xc0003f9380})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000481d40, {0x1f4a590?, 0xc000a8f1a0?}, 0xc000a0bcc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xd5c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00035cdc0, {0x1f4a590?, 0xc000a8e9c0?}, 0xc0002de380)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1c18120, 0xc00035cdc0}, {0x1f4a590, 0xc000a8e9c0}, 0xc0002de310, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d0000, {0x1f4f580, 0xc0004bc000}, 0xc000a918c0, 0xc0002f60c0, 0x28888d8, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1358 +0xde3
google.golang.org/grpc.(*Server).handleStream(0xc0001d0000, {0x1f4f580, 0xc0004bc000}, 0xc000a918c0, 0x0)
	google.golang.org/grpc@v1.57.1/server.go:1735 +0x9da
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 20
	google.golang.org/grpc@v1.57.1/server.go:981 +0x136
Error: The terraform-provider-nsxt_v3.7.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


Please let me know if you need any additional details.

Regards,
Ravi Shankar

**Comment by ksamoray** [comment]
Hi @ravishankar1jan, can you include the `nsxt_policy_lb_virtual_server ` resource which triggered the failure?

**Comment by salv-orlando** [comment]
@ksamoray this request completes and overlaps with issue #1240 - perhaps they should be both addressed with the same PR

**Comment by annakhm** [comment]
All missing resources have been merged and will be available with next provider release.
Please note that tcp and udp virtual server can be configured with existing `nsxt_policy_lb_virtual_server` resource
